events {}

http {
    upstream auth {
        server auth-service:5001;
    }

    upstream user {
        server user-service:5002;
    }

    server {
        listen 80;

        location /auth {
            proxy_pass http://auth;
        }

        location /user {
            proxy_pass http://user;
        }
    }
}